#build-stage
FROM maven:3.9.16-eclipse-temurin-21 AS build-stage
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

#package-stage
FROM eclipse-temurin:21-jdk
WORKDIR /app
COPY --from=build-stage /app/target/*.jar app.jar
EXPOSE 8086
ENTRYPOINT ["java", "-jar", "app.jar"]
