services:
  eureka-service-registry:
    build: ./Eureka-service-registry
    container_name: shoppingMicroservice-eureka-service-registry
    ports:
      - "8761:8761"
    networks:
      - shopping-network

  api-gateway:
    build: ./api-gateway
    container_name: shoppingMicroservice-api-gateway
    ports:
      - "8080:8080"
    environment:
      EUREKA_SERVER_URL: http://eureka-service-registry:8761/eureka
      SPRING_GATEWAY_SECRET: ${SPRING_GATEWAY_SECRET}
      JWT_SIGNIN_KEY: ${JWT_SIGNIN_KEY}
    depends_on:
      eureka-service-registry:
        condition: service_started
    networks:
      - shopping-network

  user-service:
    build: ./user-service
    container_name: shoppingMicroservice-user-service
    environment:
      EUREKA_SERVER_URL: http://eureka-service-registry:8761/eureka
      SPRING_DATASOURCE_URL: JDBC:mysql://user-db:3306/shopping_microservice_users
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_GATEWAY_SECRET: ${SPRING_GATEWAY_SECRET}
      JWT_SIGNIN_KEY: ${JWT_SIGNIN_KEY}
    depends_on:
      user-db:
        condition: service_healthy
      eureka-service-registry:
        condition: service_started
    networks:
      - shopping-network

  product-service:
    build: ./product-service
    container_name: shoppingMicroservice-product-service
    environment:
      EUREKA_SERVER_URL: http://eureka-service-registry:8761/eureka
      SPRING_DATASOURCE_URL: JDBC:mysql://product-db:3306/shopping_microservice_products
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_GATEWAY_SECRET: ${SPRING_GATEWAY_SECRET}
    depends_on:
      product-db:
        condition: service_healthy
      eureka-service-registry:
        condition: service_started
    networks:
      - shopping-network

  cart-service:
    build: ./cart-service
    container_name: shoppingMicroservice-cart-service
    environment:
      EUREKA_SERVER_URL: http://eureka-service-registry:8761/eureka
      SPRING_DATASOURCE_URL: JDBC:mysql://cart-db:3306/shopping_microservice_cart
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_GATEWAY_SECRET: ${SPRING_GATEWAY_SECRET}
    depends_on:
      cart-db:
        condition: service_healthy
      eureka-service-registry:
        condition: service_started
    networks:
      - shopping-network

  order-service:
    build: ./order-service
    container_name: shoppingMicroservice-order-service
    environment:
      EUREKA_SERVER_URL: http://eureka-service-registry:8761/eureka
      SPRING_DATASOURCE_URL: JDBC:mysql://order-db:3306/shopping_microservice_orders
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_GATEWAY_SECRET: ${SPRING_GATEWAY_SECRET}
    depends_on:
      order-db:
        condition: service_healthy
      eureka-service-registry:
        condition: service_started
      kafka:
        condition: service_started
    networks:
      - shopping-network

  payment-gateway-service:
    build: ./payment-gateway-service
    container_name: shoppingMicroservice-payment-gateway-service
    environment:
      EUREKA_SERVER_URL: http://eureka-service-registry:8761/eureka
      SPRING_DATASOURCE_URL: JDBC:mysql://payment-db:3306/shopping_microservice_payments
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_GATEWAY_SECRET: ${SPRING_GATEWAY_SECRET}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_KEY: ${STRIPE_WEBHOOK_KEY}
    depends_on:
      payment-db:
        condition: service_healthy
      eureka-service-registry:
        condition: service_started
      kafka:
        condition: service_started
    networks:
      - shopping-network

  stripe-cli:
    image: stripe/stripe-cli:latest
    command: listen --forward-to http://payment-gateway-service:8085/webhook/stripe
    environment:
      STRIPE_API_KEY: ${STRIPE_SECRET_KEY}
    volumes:
      - ~/.config/stripe:/root/.config/stripe
    depends_on:
      payment-gateway-service:
        condition: service_started
    networks:
      - shopping-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: "Mk3OEYBSD34fcwNTJENDM2Qk"
    networks:
      - shopping-network
    volumes:
      - kafka-volume:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - shopping-network

  user-db:
    image: mysql:latest
    container_name: shoppingMicroservice-user-db
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: shopping_microservice_users
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${SPRING_DATASOURCE_PASSWORD}" ]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - user-db-volume:/var/lib/mysql
    networks:
      - shopping-network

  product-db:
    image: mysql:latest
    container_name: shoppingMicroservice-product-db
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: shopping_microservice_products
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${SPRING_DATASOURCE_PASSWORD}" ]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - product-db-volume:/var/lib/mysql
    networks:
      - shopping-network

  cart-db:
    image: mysql:latest
    container_name: shoppingMicroservice-cart-db
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: shopping_microservice_cart
    ports:
      - "3308:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${SPRING_DATASOURCE_PASSWORD}" ]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - cart-db-volume:/var/lib/mysql
    networks:
      - shopping-network

  order-db:
    image: mysql:latest
    container_name: shoppingMicroservice-order-db
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: shopping_microservice_orders
    ports:
      - "3309:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${SPRING_DATASOURCE_PASSWORD}" ]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - order-db-volume:/var/lib/mysql
    networks:
      - shopping-network

  payment-db:
    image: mysql:latest
    container_name: shoppingMicroservice-payment-db
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: shopping_microservice_payments
    ports:
      - "3310:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${SPRING_DATASOURCE_PASSWORD}" ]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - payment-db-volume:/var/lib/mysql
    networks:
      - shopping-network

networks:
  shopping-network:

volumes:
  user-db-volume:
  product-db-volume:
  cart-db-volume:
  order-db-volume:
  payment-db-volume:
  kafka-volume: