spring:
  application:
    name: order-service
  datasource:
    url: JDBC:mysql://localhost:3306/shopping_microservice_orders
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8084

eureka:
  client:
    register-with-eureka: true

